# run: conda env create --file environment.yml
name: VuePoint
channels:
  - conda-forge
dependencies:
  - Flask==1.0.2
  - Flask-Cors==3.0.4
  - sqlalchemy
  - flask-sqlalchemy
  - flask-marshmallow
  - marshmallow-sqlalchemy
  - pip:
    - flask-wtf